# -*- coding: utf-8 -*-
"""child mortality rate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtLnA9waputmxI0OJQQwwtv-4PoL7d9c
"""

import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/data science project/data/child-mortality.csv")
df.head()

df = df[(df["Year"] >= 1957) & (df["Year"] <= 2023)]


countries = ["United States", "Japan", "China", "India", "Brazil", "Nigeria", "Ethiopia"]

plt.figure(figsize=(10, 6))

for c in countries:
    g = df[df["Entity"] == c]
    plt.plot(g["Year"], g["Child mortality rate"], label=c)

plt.xlabel("Year")
plt.ylabel("Child mortality rate")
plt.title("Child Mortality Rate (1957–2023): Selected Countries")
plt.legend()
plt.tight_layout()
plt.show()

df = pd.read_csv("/content/drive/MyDrive/data science project/data/child-mortality-gdp-per-capita.csv")
df.head()

df = df[df["Year"] == 2020]
df = df[df["Code"].notna()]   # 过滤非国家
df = df[df["Child mortality rate"].notna()]
df = df[df["GDP per capita"].notna()]

for col in ["GDP per capita", "Child mortality rate"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

plt.figure(figsize=(10, 6))

plt.scatter(
    df["GDP per capita"],
    df["Child mortality rate"],
    alpha=0.6,
    s=30
)

plt.xlabel("GDP per capita")
plt.ylabel("Child mortality rate")
plt.title("Child Mortality Rate vs GDP per capita (2020)")
df = df[df["GDP per capita"] > 0]
plt.xscale("log")  # 推荐使用 log scale，否则 GDP 分布太宽
plt.tight_layout()
plt.show()
print(len(df))
print(df["GDP per capita"])

import statsmodels.api as sm
x = df["GDP per capita"]
y = df["Child mortality rate"]
X_log = np.log(x)
X_log_const = sm.add_constant(X_log)
model = sm.OLS(y, X_log_const).fit()

print(model.summary())

plt.figure(figsize=(10, 6))

# scatter plot
plt.scatter(x, y, alpha=0.6, s=40, label="Countries")

# regression line
x_sorted = np.sort(x)
y_pred = model.predict(sm.add_constant(np.log(x_sorted)))
plt.plot(x_sorted, y_pred, color="red", linewidth=2, label="Regression line")

plt.xscale("log")
plt.xlabel("GDP per capita")
plt.ylabel("Child mortality rate")
plt.title(f"Child Mortality vs GDP per capita (Regression)")
plt.legend()
plt.tight_layout()
plt.show()